force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <label>Board</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Board Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Player Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GameController.cls
public with sharing class GameController {
    @RemoteAction
    public static List<Player__c> initGame(Integer width, Integer height, Integer playerCount){
        Board__c board = new Board__c(Width__c = width, Height__c = height);
        insert board;

        List<Player__c> players = new List<Player__c>();
        for(Integer i = 0; i < playerCount; i++){
            players.add(new Player__c(Position__c = 0, Number__c = i + 1));
        }

        insert players;
        
        players = Database.query('SELECT Number__c, Position__c FROM Player__c');

        return players;
    }
}