force-app/main/default/objects/Board__c/Board__c.object-meta.xml
<CustomObject>
    <label>Board</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Board Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Board__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Obstacle__c/Obstacle__c.object-meta.xml
<CustomObject>
    <label>Obstacle</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Obstacle Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Obstacles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Obstacle__c/fields/Board__c.field-meta.xml
<CustomField>
    <fullName>Board__c</fullName>
    <label>Board</label>
    <referenceTo>Board__c</referenceTo>
    <relationshipLabel>Obstacles</relationshipLabel>
    <relationshipName>Obstacles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Obstacle__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Obstacle__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ObstaclesService.cls
public with sharing class ObstaclesService {

    // Method to generate the obstacles of a giving board size
    public static List<Obstacle__c> generateObstacles(Board__c board){

        Integer size = board.Size__c.intValue();
        List<Obstacle__c> obstacles = new List<Obstacle__c>();
        List<Integer> used = new List<Integer>();
        Integer ctObstacle = (size * ((Math.random() * .25) + .15)).intValue();

        for(Integer i = 0; i < ctObstacle; i++){

            Integer fr = getRandomNumberNotIncluded(used, size - 1, 1);
            used.add(fr);
            Integer to = getRandomNumberNotIncluded(used, size - 1, 1);
            used.add(to);

            obstacles.add(new Obstacle__c(From__c = fr, To__c = to, Board__c = board.Id));

        }
        
        return obstacles;
    }

    // Method to get random numbers that are not included in a giving array of giving size
    public static Integer getRandomNumberNotIncluded(List<Integer> used, Integer max, Integer min){
        if(max - min == used.size()){
            throw new InfiniteLoopException('Warning preventing infinite loop');
        }

        Integer num;

        do {
            num = (Math.floor(Math.random() * (max - min)) + min).intValue();
        } while (used.contains(num));

        return num;
    }

    @TestVisible
    private class InfiniteLoopException extends Exception{}
}